# Generated by Django 4.2.4 on 2024-04-16 19:01

import dev_area_app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_inventory_item_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devinventoryitem',
            name='name',
            field=models.CharField(unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(50), dev_area_app.validators.validate_name]),
        ),
    ]
