# Generated by Django 4.2.4 on 2024-04-07 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dev_character_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.BigIntegerField()),
                ('stamina', models.BigIntegerField()),
                ('damage', models.BigIntegerField()),
                ('armor', models.BigIntegerField()),
                ('att_sp', models.DecimalField(decimal_places=2, max_digits=3)),
                ('alive', models.BooleanField(default=True)),
                ('curr_char', models.BooleanField(default=False)),
                ('level', models.BigIntegerField(default=1)),
                ('exp', models.BigIntegerField(default=0)),
                ('char_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev_character_app.devcharacter')),
            ],
        ),
    ]
