# Generated by Django 4.2.4 on 2024-04-07 17:47

import dev_area_app.validators
import dev_dialogue_options_app.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dev_area_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(50), dev_area_app.validators.validate_name])),
                ('descrip', models.TextField(validators=[django.core.validators.MinLengthValidator(4), dev_dialogue_options_app.validators.validate_text])),
                ('order', models.BigIntegerField()),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev_area_app.devarea')),
            ],
        ),
    ]
