# Generated by Django 4.2.4 on 2024-04-15 14:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import saved_game_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff_level', models.CharField(validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(6), saved_game_app.validators.validate_diff_level])),
                ('total_enemies_killed', models.BigIntegerField(default=0)),
                ('total_resources_collected', models.BigIntegerField(default=0)),
                ('total_hours_played', models.DurationField(default=0)),
                ('total_times_killed', models.BigIntegerField(default=0)),
                ('games_completed', models.BigIntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
