# Generated by Django 4.2.4 on 2024-04-21 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_stats_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestats',
            name='total_hours_played',
        ),
    ]
