# Generated by Django 4.2.4 on 2024-04-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_vol', models.BigIntegerField(default=50)),
                ('sfx_vol', models.BigIntegerField(default=50)),
                ('music_vol', models.BigIntegerField(default=50)),
            ],
        ),
    ]
