# Generated by Django 4.2.4 on 2024-04-15 14:21

import dev_dialogue_options_app.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dev_character_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevNPCDialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialogue_text', models.TextField(validators=[dev_dialogue_options_app.validators.validate_text])),
                ('char_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev_character_app.devcharacter')),
            ],
        ),
    ]
