/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Daisies.gltf 
Author: Maf'j Alvarez (https://sketchfab.com/blujay)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/margarita-flower-bush-c88faac7729b49e688dbc4d95f182168
Title: Margarita flower bush
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Daisies(props) {
  const groupRef = useRef()
  const { nodes, materials } = useGLTF('/Daisies.gltf')
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, -Math.PI]}>
        <group position={[0, 1, -3]} rotation={[0.132, 0, 0]} scale={0.25}>
          <group rotation={[2.247, 0, 0]} scale={0.937}>
            <mesh geometry={nodes.Object_7.geometry} material={materials.green} />
            <mesh geometry={nodes.Object_8.geometry} material={materials.white} />
            <mesh geometry={nodes.Object_9.geometry} material={materials.yellow} />
          </group>
          <group rotation={[2.382, 0.528, -0.487]} scale={0.732}>
            <mesh geometry={nodes.Object_11.geometry} material={materials.green} />
            <mesh geometry={nodes.Object_12.geometry} material={materials.white} />
            <mesh geometry={nodes.Object_13.geometry} material={materials.yellow} />
          </group>
          <group rotation={[1.776, 0.67, 3.059]} scale={0.937}>
            <mesh geometry={nodes.Object_15.geometry} material={materials.green} />
            <mesh geometry={nodes.Object_16.geometry} material={materials.white} />
            <mesh geometry={nodes.Object_17.geometry} material={materials.yellow} />
          </group>
          <group rotation={[1.737, -0.253, -3.054]} scale={0.824}>
            <mesh geometry={nodes.Object_19.geometry} material={materials.green} />
            <mesh geometry={nodes.Object_20.geometry} material={materials.white} />
            <mesh geometry={nodes.Object_21.geometry} material={materials.yellow} />
          </group>
          <group rotation={[2.541, -0.253, -3.054]} scale={0.562}>
            <mesh geometry={nodes.Object_23.geometry} material={materials.green} />
            <mesh geometry={nodes.Object_24.geometry} material={materials.white} />
            <mesh geometry={nodes.Object_25.geometry} material={materials.yellow} />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_27.geometry} material={materials.green} />
            <mesh geometry={nodes.Object_28.geometry} material={materials.white} />
            <mesh geometry={nodes.Object_29.geometry} material={materials.yellow} />
          </group>
          <group rotation={[1.142, 0.67, 3.059]} scale={1.017}>
            <mesh geometry={nodes.Object_31.geometry} material={materials.green} />
            <mesh geometry={nodes.Object_32.geometry} material={materials.white} />
            <mesh geometry={nodes.Object_33.geometry} material={materials.yellow} />
          </group>
          <group position={[0.022, 0.519, -0.007]} rotation={[1.669, 0.956, -0.189]} scale={0.508}>
            <mesh geometry={nodes.Object_35.geometry} material={materials.green} />
            <mesh geometry={nodes.Object_36.geometry} material={materials.white} />
            <mesh geometry={nodes.Object_37.geometry} material={materials.yellow} />
          </group>
          <group position={[0.022, 0.519, -0.007]} rotation={[0.503, 0.329, 1.427]} scale={0.882}>
            <mesh geometry={nodes.Object_39.geometry} material={materials.green} />
            <mesh geometry={nodes.Object_40.geometry} material={materials.white} />
            <mesh geometry={nodes.Object_41.geometry} material={materials.yellow} />
          </group>
          <group position={[0.022, 0.519, -0.007]} rotation={[0.961, -0.099, 0.992]} scale={0.745}>
            <mesh geometry={nodes.Object_43.geometry} material={materials.green} />
            <mesh geometry={nodes.Object_44.geometry} material={materials.white} />
            <mesh geometry={nodes.Object_45.geometry} material={materials.yellow} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Daisies.gltf')
