/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 FlowerBush.gltf 
Author: Juandaneitor master (https://sketchfab.com/juandavidchibuque)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bush-with-flowers-609994baf89d4bf5a95f12f7dd5e77fe
Title: Bush With Flowers
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function FlowerBush(props) {
  const groupRef = useRef()
  const { nodes, materials } = useGLTF('/FlowerBush.gltf')
  return (
    <>
      <group ref={groupRef} {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={0.24} position={[-4.3, 0, -11]}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.Bush1Mtl} />
          <mesh geometry={nodes.Object_3.geometry} material={materials.Meshpart1Mtl} />
        </group>
      </group>

      <group ref={groupRef} {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={0.24} position={[-1, 0, -12]}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.Bush1Mtl} />
          <mesh geometry={nodes.Object_3.geometry} material={materials.Meshpart1Mtl} />
        </group>
      </group>
    </>
  )
}

useGLTF.preload('/FlowerBush.gltf')
