/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 PicnicTable.gltf 
Author: Derek Flanagan (https://sketchfab.com/derek_flanagan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/picnic-table-low-poly-fe35acda3a5245da8459d1a062e28190
Title: Picnic Table - Low Poly
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const groupRef = useRef()
  const { nodes, materials } = useGLTF('/PicnicTable.gltf')
  return (
    <>
      <group ref={groupRef} {...props} dispose={null}>
        <group rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.024}>
          <mesh geometry={nodes.PicnicTable_Picnic_Table_0.geometry} material={materials.Picnic_Table} rotation={[-Math.PI, 0, 0]} position={[0, 650, 0]} />
        </group>
      </group>

      <group ref={groupRef} {...props} dispose={null}>
        <group rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.024}>
          <mesh geometry={nodes.PicnicTable_Picnic_Table_0.geometry} material={materials.Picnic_Table} rotation={[-Math.PI, 0, 0]} position={[200, 650, 0]} />
        </group>
      </group>

      <group ref={groupRef} {...props} dispose={null}>
        <group rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.024}>
          <mesh geometry={nodes.PicnicTable_Picnic_Table_0.geometry} material={materials.Picnic_Table} rotation={[-Math.PI, 0, 0]} position={[400, 650, 0]} />
        </group>
      </group>

      <group ref={groupRef} {...props} dispose={null}>
        <group rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.024}>
          <mesh geometry={nodes.PicnicTable_Picnic_Table_0.geometry} material={materials.Picnic_Table} rotation={[-Math.PI, 0, 0]} position={[150, -950, 30]} />
        </group>
      </group>
    </>
  )
}

useGLTF.preload('/PicnicTable.gltf')
