/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 SunsetFlowerBush.gltf 
Author: Aaron Wilson (https://sketchfab.com/aaronbwilson2001)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flower-bush-765a6a546d7545f8b9a83cc7a17a9199
Title: Flower bush
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function SunsetFlowerBush(props) {
  const groupRef = useRef()
  const { nodes, materials } = useGLTF('/SunsetFlowerBush.gltf')
  return (
    <>
      <group ref={groupRef} {...props} dispose={null}>
        <group rotation={[-0.3, 0.3, 0]} scale={0.015} position={[-2, 3.5, -12.2]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[5.688, 0, -12]}>
              <group position={[-10.836, 15.481, 20.919]} rotation={[-2.937, -0.208, -3.099]}>
                <group position={[-20, 0, 0]} scale={1.111}>
                  <mesh geometry={nodes.Bush_leaf13_Leaf_0.geometry} material={materials.Leaf} position={[-3.783, -4.046, 15.452]} rotation={[0, -1.257, 2.467]} />
                  <mesh geometry={nodes.Bush_leaf14_Leaf_0.geometry} material={materials.Leaf} position={[-2.838, -0.528, 0.816]} rotation={[2.791, -0.203, 2.88]} scale={0.914} />
                  <mesh geometry={nodes.Bush_leaf15_Leaf_0.geometry} material={materials.Leaf} position={[-1.452, -2.571, 12.134]} rotation={[-1.494, 1.509, 1.882]} scale={0.768} />
                  <mesh geometry={nodes.Bush_leaf16_Leaf_0.geometry} material={materials.Leaf} rotation={[0.056, 1.042, -0.521]} scale={0.964} />
                  <mesh geometry={nodes.Bush_leaf17_Leaf_0.geometry} material={materials.Leaf} rotation={[-0.882, -1.098, -0.824]} />
                  <mesh geometry={nodes.Bush_leaf18_Leaf_0.geometry} material={materials.Leaf} rotation={[2.775, -0.722, -2.943]} scale={1.081} />
                  <mesh geometry={nodes.Bush_leaf19_Leaf_0.geometry} material={materials.Leaf} rotation={[-1.096, -0.353, 2.317]} />
                  <mesh geometry={nodes.Bush_leaf20_Leaf_0.geometry} material={materials.Leaf} position={[9.65, -0.937, -0.005]} rotation={[-2.932, 0.091, -2.794]} />
                </group>
                <group position={[-9.741, -2.987, 18.859]} rotation={[0, -0.686, 0]} scale={0.975}>
                  <mesh geometry={nodes.Bush_leaf13_Leaf_0_1.geometry} material={materials.Leaf} position={[-3.783, -4.046, 15.452]} rotation={[0, -1.257, 2.467]} />
                  <mesh geometry={nodes.Bush_leaf14_Leaf_0_1.geometry} material={materials.Leaf} position={[-2.838, -0.528, 0.816]} rotation={[2.791, -0.203, 2.88]} scale={0.914} />
                  <mesh geometry={nodes.Bush_leaf15_Leaf_0_1.geometry} material={materials.Leaf} position={[-1.452, -2.571, 12.134]} rotation={[-1.494, 1.509, 1.882]} scale={0.768} />
                  <mesh geometry={nodes.Bush_leaf16_Leaf_0_1.geometry} material={materials.Leaf} rotation={[0.056, 1.042, -0.521]} scale={0.964} />
                  <mesh geometry={nodes.Bush_leaf17_Leaf_0_1.geometry} material={materials.Leaf} rotation={[-0.882, -1.098, -0.824]} />
                  <mesh geometry={nodes.Bush_leaf18_Leaf_0_1.geometry} material={materials.Leaf} rotation={[2.775, -0.722, -2.943]} scale={1.081} />
                  <mesh geometry={nodes.Bush_leaf19_Leaf_0_1.geometry} material={materials.Leaf} rotation={[-1.096, -0.353, 2.317]} />
                  <mesh geometry={nodes.Bush_leaf20_Leaf_0_1.geometry} material={materials.Leaf} position={[9.65, -0.937, -0.005]} rotation={[-2.932, 0.091, -2.794]} />
                </group>
                <group position={[9.175, -6.127, 14.116]} rotation={[0, -0.409, 0]}>
                  <mesh geometry={nodes.Bush_leaf13_Leaf_0_2.geometry} material={materials.Leaf} position={[-3.783, -4.046, 15.452]} rotation={[0, -1.257, 2.467]} />
                  <mesh geometry={nodes.Bush_leaf14_Leaf_0_2.geometry} material={materials.Leaf} position={[-2.838, -0.528, 0.816]} rotation={[2.791, -0.203, 2.88]} scale={0.914} />
                  <mesh geometry={nodes.Bush_leaf15_Leaf_0_2.geometry} material={materials.Leaf} position={[-1.452, -2.571, 12.134]} rotation={[-1.494, 1.509, 1.882]} scale={0.768} />
                  <mesh geometry={nodes.Bush_leaf16_Leaf_0_2.geometry} material={materials.Leaf} rotation={[0.056, 1.042, -0.521]} scale={0.964} />
                  <mesh geometry={nodes.Bush_leaf17_Leaf_0_2.geometry} material={materials.Leaf} rotation={[-0.882, -1.098, -0.824]} />
                  <mesh geometry={nodes.Bush_leaf18_Leaf_0_2.geometry} material={materials.Leaf} rotation={[2.775, -0.722, -2.943]} scale={1.081} />
                  <mesh geometry={nodes.Bush_leaf19_Leaf_0_2.geometry} material={materials.Leaf} rotation={[-1.096, -0.353, 2.317]} />
                  <mesh geometry={nodes.Bush_leaf20_Leaf_0_2.geometry} material={materials.Leaf} position={[9.65, -0.937, -0.005]} rotation={[-2.932, 0.091, -2.794]} />
                </group>
                <mesh geometry={nodes.Bush_leaf21_Leaf_0.geometry} material={materials.Leaf} position={[-1.452, -2.571, 12.134]} rotation={[-1.494, 1.509, 1.882]} scale={0.768} />
                <mesh geometry={nodes.Bush_leaf22_Leaf_0.geometry} material={materials.Leaf} position={[-3.783, -4.046, 15.452]} rotation={[0, -1.257, 2.467]} />
                <mesh geometry={nodes.Bush_leaf23_Leaf_0.geometry} material={materials.Leaf} position={[-2.838, -0.528, 0.816]} rotation={[2.791, -0.203, 2.88]} scale={0.914} />
                <mesh geometry={nodes.Bush_leaf24_Leaf_0.geometry} material={materials.Leaf} rotation={[2.775, -0.722, -2.943]} scale={1.081} />
                <mesh geometry={nodes.Bush_leaf25_Leaf_0.geometry} material={materials.Leaf} rotation={[-1.096, -0.353, 2.317]} />
                <mesh geometry={nodes.Bush_leaf26_Leaf_0.geometry} material={materials.Leaf} rotation={[-0.882, -1.098, -0.824]} />
                <mesh geometry={nodes.Bush_leaf27_Leaf_0.geometry} material={materials.Leaf} rotation={[0.056, 1.042, -0.521]} scale={0.964} />
                <mesh geometry={nodes.Bush_leaf28_Leaf_0.geometry} material={materials.Leaf} position={[9.65, -0.937, -0.005]} rotation={[-2.932, 0.091, -2.794]} />
              </group>
              <group position={[0, 28, 0]}>
                <group position={[-20, 0, 0]} scale={1.111}>
                  <mesh geometry={nodes.Bush_leaf13_Leaf_0_3.geometry} material={materials.Leaf} position={[-3.783, -4.046, 15.452]} rotation={[0, -1.257, 2.467]} />
                  <mesh geometry={nodes.Bush_leaf14_Leaf_0_3.geometry} material={materials.Leaf} position={[-2.838, -0.528, 0.816]} rotation={[2.791, -0.203, 2.88]} scale={0.914} />
                  <mesh geometry={nodes.Bush_leaf15_Leaf_0_3.geometry} material={materials.Leaf} position={[-1.452, -2.571, 12.134]} rotation={[-1.494, 1.509, 1.882]} scale={0.768} />
                  <mesh geometry={nodes.Bush_leaf16_Leaf_0_3.geometry} material={materials.Leaf} rotation={[0.056, 1.042, -0.521]} scale={0.964} />
                  <mesh geometry={nodes.Bush_leaf17_Leaf_0_3.geometry} material={materials.Leaf} rotation={[-0.882, -1.098, -0.824]} />
                  <mesh geometry={nodes.Bush_leaf18_Leaf_0_3.geometry} material={materials.Leaf} rotation={[2.775, -0.722, -2.943]} scale={1.081} />
                  <mesh geometry={nodes.Bush_leaf19_Leaf_0_3.geometry} material={materials.Leaf} rotation={[-1.096, -0.353, 2.317]} />
                  <mesh geometry={nodes.Bush_leaf20_Leaf_0_3.geometry} material={materials.Leaf} position={[9.65, -0.937, -0.005]} rotation={[-2.932, 0.091, -2.794]} />
                </group>
                <group position={[-9.741, -2.987, 18.859]} rotation={[0, -0.686, 0]} scale={0.975}>
                  <mesh geometry={nodes.Bush_leaf13_Leaf_0_4.geometry} material={materials.Leaf} position={[-3.783, -4.046, 15.452]} rotation={[0, -1.257, 2.467]} />
                  <mesh geometry={nodes.Bush_leaf14_Leaf_0_4.geometry} material={materials.Leaf} position={[-2.838, -0.528, 0.816]} rotation={[2.791, -0.203, 2.88]} scale={0.914} />
                  <mesh geometry={nodes.Bush_leaf15_Leaf_0_4.geometry} material={materials.Leaf} position={[-1.452, -2.571, 12.134]} rotation={[-1.494, 1.509, 1.882]} scale={0.768} />
                  <mesh geometry={nodes.Bush_leaf16_Leaf_0_4.geometry} material={materials.Leaf} rotation={[0.056, 1.042, -0.521]} scale={0.964} />
                  <mesh geometry={nodes.Bush_leaf17_Leaf_0_4.geometry} material={materials.Leaf} rotation={[-0.882, -1.098, -0.824]} />
                  <mesh geometry={nodes.Bush_leaf18_Leaf_0_4.geometry} material={materials.Leaf} rotation={[2.775, -0.722, -2.943]} scale={1.081} />
                  <mesh geometry={nodes.Bush_leaf19_Leaf_0_4.geometry} material={materials.Leaf} rotation={[-1.096, -0.353, 2.317]} />
                  <mesh geometry={nodes.Bush_leaf20_Leaf_0_4.geometry} material={materials.Leaf} position={[9.65, -0.937, -0.005]} rotation={[-2.932, 0.091, -2.794]} />
                </group>
                <group position={[9.175, -6.127, 14.116]} rotation={[0, -0.409, 0]}>
                  <mesh geometry={nodes.Bush_leaf13_Leaf_0_5.geometry} material={materials.Leaf} position={[-3.783, -4.046, 15.452]} rotation={[0, -1.257, 2.467]} />
                  <mesh geometry={nodes.Bush_leaf14_Leaf_0_5.geometry} material={materials.Leaf} position={[-2.838, -0.528, 0.816]} rotation={[2.791, -0.203, 2.88]} scale={0.914} />
                  <mesh geometry={nodes.Bush_leaf15_Leaf_0_5.geometry} material={materials.Leaf} position={[-1.452, -2.571, 12.134]} rotation={[-1.494, 1.509, 1.882]} scale={0.768} />
                  <mesh geometry={nodes.Bush_leaf16_Leaf_0_5.geometry} material={materials.Leaf} rotation={[0.056, 1.042, -0.521]} scale={0.964} />
                  <mesh geometry={nodes.Bush_leaf17_Leaf_0_5.geometry} material={materials.Leaf} rotation={[-0.882, -1.098, -0.824]} />
                  <mesh geometry={nodes.Bush_leaf18_Leaf_0_5.geometry} material={materials.Leaf} rotation={[2.775, -0.722, -2.943]} scale={1.081} />
                  <mesh geometry={nodes.Bush_leaf19_Leaf_0_5.geometry} material={materials.Leaf} rotation={[-1.096, -0.353, 2.317]} />
                  <mesh geometry={nodes.Bush_leaf20_Leaf_0_5.geometry} material={materials.Leaf} position={[9.65, -0.937, -0.005]} rotation={[-2.932, 0.091, -2.794]} />
                </group>
                <mesh geometry={nodes.Bush_leaf21_Leaf_0_1.geometry} material={materials.Leaf} position={[-1.452, -2.571, 12.134]} rotation={[-1.494, 1.509, 1.882]} scale={0.768} />
                <mesh geometry={nodes.Bush_leaf22_Leaf_0_1.geometry} material={materials.Leaf} position={[-3.783, -4.046, 15.452]} rotation={[0, -1.257, 2.467]} />
                <mesh geometry={nodes.Bush_leaf23_Leaf_0_1.geometry} material={materials.Leaf} position={[-2.838, -0.528, 0.816]} rotation={[2.791, -0.203, 2.88]} scale={0.914} />
                <mesh geometry={nodes.Bush_leaf24_Leaf_0_1.geometry} material={materials.Leaf} rotation={[2.775, -0.722, -2.943]} scale={1.081} />
                <mesh geometry={nodes.Bush_leaf25_Leaf_0_1.geometry} material={materials.Leaf} rotation={[-1.096, -0.353, 2.317]} />
                <mesh geometry={nodes.Bush_leaf26_Leaf_0_1.geometry} material={materials.Leaf} rotation={[-0.882, -1.098, -0.824]} />
                <mesh geometry={nodes.Bush_leaf27_Leaf_0_1.geometry} material={materials.Leaf} rotation={[0.056, 1.042, -0.521]} scale={0.964} />
                <mesh geometry={nodes.Bush_leaf28_Leaf_0_1.geometry} material={materials.Leaf} position={[9.65, -0.937, -0.005]} rotation={[-2.932, 0.091, -2.794]} />
              </group>
            </group>
            <group position={[12.44, 28.804, 9.471]} rotation={[0.718, 0.154, -0.123]}>
              <mesh geometry={nodes.Petal_shaped7_Petal1_0.geometry} material={materials.Petal1} rotation={[0, 1.309, -0.579]} />
              <mesh geometry={nodes.Petal_shaped9_Petal1_0.geometry} material={materials.Petal1} rotation={[-Math.PI, -0.348, -Math.PI]} />
              <mesh geometry={nodes.Petal_shaped8_Petal1_0.geometry} material={materials.Petal1} rotation={[2.706, -1.31, 3.012]} />
              <mesh geometry={nodes.Petal_shaped11_Petal1_0.geometry} material={materials.Petal1} rotation={[0, -0.856, -0.36]} />
              <mesh geometry={nodes.Petal_shaped13_Petal1_0.geometry} material={materials.Petal1} rotation={[-1.094, -1.359, -1.004]} />
              <mesh geometry={nodes.Petal_shaped5_Petal1_0.geometry} material={materials.Petal1} rotation={[0, -0.182, 0]} />
              <mesh geometry={nodes.Petal_shaped12_Petal1_0.geometry} material={materials.Petal1} rotation={[-0.122, 0.26, -0.342]} />
              <mesh geometry={nodes.Petal_shaped19_Petal1_0.geometry} material={materials.Petal1} rotation={[2.673, -0.864, -2.953]} />
              <mesh geometry={nodes.Petal_shaped10_Petal1_0.geometry} material={materials.Petal1} rotation={[-Math.PI, 0.702, -Math.PI]} />
              <mesh geometry={nodes.Petal_shaped6_Petal1_0.geometry} material={materials.Petal1} rotation={[0, 0.504, -0.714]} />
              <mesh geometry={nodes.Petal_shaped27_Petal1_0.geometry} material={materials.Petal1} rotation={[-2.956, 0.242, 1.904]} />
              <mesh geometry={nodes.Petal_shaped25_Petal1_0.geometry} material={materials.Petal1} rotation={[-0.147, -1.364, -0.938]} />
              <mesh geometry={nodes.Petal_shaped26_Petal1_0.geometry} material={materials.Petal1} rotation={[0.009, 0.221, -1.066]} />
              <mesh geometry={nodes.Petal_shaped20_Petal1_0.geometry} material={materials.Petal1} rotation={[-0.291, -0.532, 0.387]} />
              <mesh geometry={nodes.Petal_shaped23_Petal1_0.geometry} material={materials.Petal1} rotation={[-3.111, -0.528, 2.258]} />
              <mesh geometry={nodes.Petal_shaped21_Petal1_0.geometry} material={materials.Petal1} rotation={[-1.869, 1.301, 2.174]} />
              <mesh geometry={nodes.Petal_shaped22_Petal1_0.geometry} material={materials.Petal1} rotation={[-0.26, -0.396, -0.836]} />
              <mesh geometry={nodes.Petal_shaped24_Petal1_0.geometry} material={materials.Petal1} rotation={[-2.766, 1.252, 1.841]} />
              <mesh geometry={nodes.Petal_shaped17_Petal1_0.geometry} material={materials.Petal1} rotation={[3, -1.037, 2.717]} />
              <mesh geometry={nodes.Petal_shaped16_Petal1_0.geometry} material={materials.Petal1} rotation={[0.851, 1.071, -0.814]} />
              <mesh geometry={nodes.Petal_shaped14_Petal1_0.geometry} material={materials.Petal1} rotation={[3.074, 1.41, 2.907]} />
              <mesh geometry={nodes.Petal_shaped15_Petal1_0.geometry} material={materials.Petal1} rotation={[-Math.PI, 0.266, 2.602]} />
            </group>
            <group position={[-5.79, 32.512, -15.281]} rotation={[-0.984, 0.827, 0.419]}>
              <mesh geometry={nodes.Petal_shaped7_Petal1_0_1.geometry} material={materials.Petal1} rotation={[0, 1.309, -0.579]} />
              <mesh geometry={nodes.Petal_shaped9_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-Math.PI, -0.348, -Math.PI]} />
              <mesh geometry={nodes.Petal_shaped8_Petal1_0_1.geometry} material={materials.Petal1} rotation={[2.706, -1.31, 3.012]} />
              <mesh geometry={nodes.Petal_shaped11_Petal1_0_1.geometry} material={materials.Petal1} rotation={[0, -0.856, -0.36]} />
              <mesh geometry={nodes.Petal_shaped13_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-1.094, -1.359, -1.004]} />
              <mesh geometry={nodes.Petal_shaped5_Petal1_0_1.geometry} material={materials.Petal1} rotation={[0, -0.182, 0]} />
              <mesh geometry={nodes.Petal_shaped12_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-0.122, 0.26, -0.342]} />
              <mesh geometry={nodes.Petal_shaped19_Petal1_0_1.geometry} material={materials.Petal1} rotation={[2.673, -0.864, -2.953]} />
              <mesh geometry={nodes.Petal_shaped10_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-Math.PI, 0.702, -Math.PI]} />
              <mesh geometry={nodes.Petal_shaped6_Petal1_0_1.geometry} material={materials.Petal1} rotation={[0, 0.504, -0.714]} />
              <mesh geometry={nodes.Petal_shaped27_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-2.956, 0.242, 1.904]} />
              <mesh geometry={nodes.Petal_shaped25_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-0.147, -1.364, -0.938]} />
              <mesh geometry={nodes.Petal_shaped26_Petal1_0_1.geometry} material={materials.Petal1} rotation={[0.009, 0.221, -1.066]} />
              <mesh geometry={nodes.Petal_shaped20_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-0.291, -0.532, 0.387]} />
              <mesh geometry={nodes.Petal_shaped23_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-3.111, -0.528, 2.258]} />
              <mesh geometry={nodes.Petal_shaped21_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-1.869, 1.301, 2.174]} />
              <mesh geometry={nodes.Petal_shaped22_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-0.26, -0.396, -0.836]} />
              <mesh geometry={nodes.Petal_shaped24_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-2.766, 1.252, 1.841]} />
              <mesh geometry={nodes.Petal_shaped17_Petal1_0_1.geometry} material={materials.Petal1} rotation={[3, -1.037, 2.717]} />
              <mesh geometry={nodes.Petal_shaped16_Petal1_0_1.geometry} material={materials.Petal1} rotation={[0.851, 1.071, -0.814]} />
              <mesh geometry={nodes.Petal_shaped14_Petal1_0_1.geometry} material={materials.Petal1} rotation={[3.074, 1.41, 2.907]} />
              <mesh geometry={nodes.Petal_shaped15_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-Math.PI, 0.266, 2.602]} />
            </group>
            <group position={[-14.51, 26.053, 15.323]} rotation={[0.137, 0.43, 0.991]}>
              <mesh geometry={nodes.Petal_shaped7_Petal1_0_2.geometry} material={materials.Petal1} rotation={[0, 1.309, -0.579]} />
              <mesh geometry={nodes.Petal_shaped9_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-Math.PI, -0.348, Math.PI]} />
              <mesh geometry={nodes.Petal_shaped8_Petal1_0_2.geometry} material={materials.Petal1} rotation={[2.706, -1.31, 3.012]} />
              <mesh geometry={nodes.Petal_shaped11_Petal1_0_2.geometry} material={materials.Petal1} rotation={[0, -0.856, -0.36]} />
              <mesh geometry={nodes.Petal_shaped13_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-1.094, -1.359, -1.004]} />
              <mesh geometry={nodes.Petal_shaped5_Petal1_0_2.geometry} material={materials.Petal1} rotation={[0, -0.182, 0]} />
              <mesh geometry={nodes.Petal_shaped12_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-0.122, 0.26, -0.342]} />
              <mesh geometry={nodes.Petal_shaped19_Petal1_0_2.geometry} material={materials.Petal1} rotation={[2.673, -0.864, -2.953]} />
              <mesh geometry={nodes.Petal_shaped10_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-Math.PI, 0.702, -Math.PI]} />
              <mesh geometry={nodes.Petal_shaped6_Petal1_0_2.geometry} material={materials.Petal1} rotation={[0, 0.504, -0.714]} />
              <mesh geometry={nodes.Petal_shaped27_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-2.956, 0.242, 1.904]} />
              <mesh geometry={nodes.Petal_shaped25_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-0.147, -1.364, -0.938]} />
              <mesh geometry={nodes.Petal_shaped26_Petal1_0_2.geometry} material={materials.Petal1} rotation={[0.009, 0.221, -1.066]} />
              <mesh geometry={nodes.Petal_shaped20_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-0.291, -0.532, 0.387]} />
              <mesh geometry={nodes.Petal_shaped23_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-3.111, -0.528, 2.258]} />
              <mesh geometry={nodes.Petal_shaped21_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-1.869, 1.301, 2.174]} />
              <mesh geometry={nodes.Petal_shaped22_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-0.26, -0.396, -0.836]} />
              <mesh geometry={nodes.Petal_shaped24_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-2.766, 1.252, 1.841]} />
              <mesh geometry={nodes.Petal_shaped17_Petal1_0_2.geometry} material={materials.Petal1} rotation={[3, -1.037, 2.717]} />
              <mesh geometry={nodes.Petal_shaped16_Petal1_0_2.geometry} material={materials.Petal1} rotation={[0.851, 1.071, -0.814]} />
              <mesh geometry={nodes.Petal_shaped14_Petal1_0_2.geometry} material={materials.Petal1} rotation={[3.074, 1.41, 2.907]} />
              <mesh geometry={nodes.Petal_shaped15_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-Math.PI, 0.266, 2.602]} />
            </group>
          </group>
        </group>
      </group>

      <group ref={groupRef} {...props} dispose={null}>
        <group rotation={[-0.3, 0.2, 0]} scale={0.015} position={[-2.5, 3.5, -12]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[5.688, 0, -12]}>
              <group position={[-10.836, 15.481, 20.919]} rotation={[-2.937, -0.208, -3.099]}>
                <group position={[-20, 0, 0]} scale={1.111}>
                  <mesh geometry={nodes.Bush_leaf13_Leaf_0.geometry} material={materials.Leaf} position={[-3.783, -4.046, 15.452]} rotation={[0, -1.257, 2.467]} />
                  <mesh geometry={nodes.Bush_leaf14_Leaf_0.geometry} material={materials.Leaf} position={[-2.838, -0.528, 0.816]} rotation={[2.791, -0.203, 2.88]} scale={0.914} />
                  <mesh geometry={nodes.Bush_leaf15_Leaf_0.geometry} material={materials.Leaf} position={[-1.452, -2.571, 12.134]} rotation={[-1.494, 1.509, 1.882]} scale={0.768} />
                  <mesh geometry={nodes.Bush_leaf16_Leaf_0.geometry} material={materials.Leaf} rotation={[0.056, 1.042, -0.521]} scale={0.964} />
                  <mesh geometry={nodes.Bush_leaf17_Leaf_0.geometry} material={materials.Leaf} rotation={[-0.882, -1.098, -0.824]} />
                  <mesh geometry={nodes.Bush_leaf18_Leaf_0.geometry} material={materials.Leaf} rotation={[2.775, -0.722, -2.943]} scale={1.081} />
                  <mesh geometry={nodes.Bush_leaf19_Leaf_0.geometry} material={materials.Leaf} rotation={[-1.096, -0.353, 2.317]} />
                  <mesh geometry={nodes.Bush_leaf20_Leaf_0.geometry} material={materials.Leaf} position={[9.65, -0.937, -0.005]} rotation={[-2.932, 0.091, -2.794]} />
                </group>
                <group position={[-9.741, -2.987, 18.859]} rotation={[0, -0.686, 0]} scale={0.975}>
                  <mesh geometry={nodes.Bush_leaf13_Leaf_0_1.geometry} material={materials.Leaf} position={[-3.783, -4.046, 15.452]} rotation={[0, -1.257, 2.467]} />
                  <mesh geometry={nodes.Bush_leaf14_Leaf_0_1.geometry} material={materials.Leaf} position={[-2.838, -0.528, 0.816]} rotation={[2.791, -0.203, 2.88]} scale={0.914} />
                  <mesh geometry={nodes.Bush_leaf15_Leaf_0_1.geometry} material={materials.Leaf} position={[-1.452, -2.571, 12.134]} rotation={[-1.494, 1.509, 1.882]} scale={0.768} />
                  <mesh geometry={nodes.Bush_leaf16_Leaf_0_1.geometry} material={materials.Leaf} rotation={[0.056, 1.042, -0.521]} scale={0.964} />
                  <mesh geometry={nodes.Bush_leaf17_Leaf_0_1.geometry} material={materials.Leaf} rotation={[-0.882, -1.098, -0.824]} />
                  <mesh geometry={nodes.Bush_leaf18_Leaf_0_1.geometry} material={materials.Leaf} rotation={[2.775, -0.722, -2.943]} scale={1.081} />
                  <mesh geometry={nodes.Bush_leaf19_Leaf_0_1.geometry} material={materials.Leaf} rotation={[-1.096, -0.353, 2.317]} />
                  <mesh geometry={nodes.Bush_leaf20_Leaf_0_1.geometry} material={materials.Leaf} position={[9.65, -0.937, -0.005]} rotation={[-2.932, 0.091, -2.794]} />
                </group>
                <group position={[9.175, -6.127, 14.116]} rotation={[0, -0.409, 0]}>
                  <mesh geometry={nodes.Bush_leaf13_Leaf_0_2.geometry} material={materials.Leaf} position={[-3.783, -4.046, 15.452]} rotation={[0, -1.257, 2.467]} />
                  <mesh geometry={nodes.Bush_leaf14_Leaf_0_2.geometry} material={materials.Leaf} position={[-2.838, -0.528, 0.816]} rotation={[2.791, -0.203, 2.88]} scale={0.914} />
                  <mesh geometry={nodes.Bush_leaf15_Leaf_0_2.geometry} material={materials.Leaf} position={[-1.452, -2.571, 12.134]} rotation={[-1.494, 1.509, 1.882]} scale={0.768} />
                  <mesh geometry={nodes.Bush_leaf16_Leaf_0_2.geometry} material={materials.Leaf} rotation={[0.056, 1.042, -0.521]} scale={0.964} />
                  <mesh geometry={nodes.Bush_leaf17_Leaf_0_2.geometry} material={materials.Leaf} rotation={[-0.882, -1.098, -0.824]} />
                  <mesh geometry={nodes.Bush_leaf18_Leaf_0_2.geometry} material={materials.Leaf} rotation={[2.775, -0.722, -2.943]} scale={1.081} />
                  <mesh geometry={nodes.Bush_leaf19_Leaf_0_2.geometry} material={materials.Leaf} rotation={[-1.096, -0.353, 2.317]} />
                  <mesh geometry={nodes.Bush_leaf20_Leaf_0_2.geometry} material={materials.Leaf} position={[9.65, -0.937, -0.005]} rotation={[-2.932, 0.091, -2.794]} />
                </group>
                <mesh geometry={nodes.Bush_leaf21_Leaf_0.geometry} material={materials.Leaf} position={[-1.452, -2.571, 12.134]} rotation={[-1.494, 1.509, 1.882]} scale={0.768} />
                <mesh geometry={nodes.Bush_leaf22_Leaf_0.geometry} material={materials.Leaf} position={[-3.783, -4.046, 15.452]} rotation={[0, -1.257, 2.467]} />
                <mesh geometry={nodes.Bush_leaf23_Leaf_0.geometry} material={materials.Leaf} position={[-2.838, -0.528, 0.816]} rotation={[2.791, -0.203, 2.88]} scale={0.914} />
                <mesh geometry={nodes.Bush_leaf24_Leaf_0.geometry} material={materials.Leaf} rotation={[2.775, -0.722, -2.943]} scale={1.081} />
                <mesh geometry={nodes.Bush_leaf25_Leaf_0.geometry} material={materials.Leaf} rotation={[-1.096, -0.353, 2.317]} />
                <mesh geometry={nodes.Bush_leaf26_Leaf_0.geometry} material={materials.Leaf} rotation={[-0.882, -1.098, -0.824]} />
                <mesh geometry={nodes.Bush_leaf27_Leaf_0.geometry} material={materials.Leaf} rotation={[0.056, 1.042, -0.521]} scale={0.964} />
                <mesh geometry={nodes.Bush_leaf28_Leaf_0.geometry} material={materials.Leaf} position={[9.65, -0.937, -0.005]} rotation={[-2.932, 0.091, -2.794]} />
              </group>
              <group position={[0, 28, 0]}>
                <group position={[-20, 0, 0]} scale={1.111}>
                  <mesh geometry={nodes.Bush_leaf13_Leaf_0_3.geometry} material={materials.Leaf} position={[-3.783, -4.046, 15.452]} rotation={[0, -1.257, 2.467]} />
                  <mesh geometry={nodes.Bush_leaf14_Leaf_0_3.geometry} material={materials.Leaf} position={[-2.838, -0.528, 0.816]} rotation={[2.791, -0.203, 2.88]} scale={0.914} />
                  <mesh geometry={nodes.Bush_leaf15_Leaf_0_3.geometry} material={materials.Leaf} position={[-1.452, -2.571, 12.134]} rotation={[-1.494, 1.509, 1.882]} scale={0.768} />
                  <mesh geometry={nodes.Bush_leaf16_Leaf_0_3.geometry} material={materials.Leaf} rotation={[0.056, 1.042, -0.521]} scale={0.964} />
                  <mesh geometry={nodes.Bush_leaf17_Leaf_0_3.geometry} material={materials.Leaf} rotation={[-0.882, -1.098, -0.824]} />
                  <mesh geometry={nodes.Bush_leaf18_Leaf_0_3.geometry} material={materials.Leaf} rotation={[2.775, -0.722, -2.943]} scale={1.081} />
                  <mesh geometry={nodes.Bush_leaf19_Leaf_0_3.geometry} material={materials.Leaf} rotation={[-1.096, -0.353, 2.317]} />
                  <mesh geometry={nodes.Bush_leaf20_Leaf_0_3.geometry} material={materials.Leaf} position={[9.65, -0.937, -0.005]} rotation={[-2.932, 0.091, -2.794]} />
                </group>
                <group position={[-9.741, -2.987, 18.859]} rotation={[0, -0.686, 0]} scale={0.975}>
                  <mesh geometry={nodes.Bush_leaf13_Leaf_0_4.geometry} material={materials.Leaf} position={[-3.783, -4.046, 15.452]} rotation={[0, -1.257, 2.467]} />
                  <mesh geometry={nodes.Bush_leaf14_Leaf_0_4.geometry} material={materials.Leaf} position={[-2.838, -0.528, 0.816]} rotation={[2.791, -0.203, 2.88]} scale={0.914} />
                  <mesh geometry={nodes.Bush_leaf15_Leaf_0_4.geometry} material={materials.Leaf} position={[-1.452, -2.571, 12.134]} rotation={[-1.494, 1.509, 1.882]} scale={0.768} />
                  <mesh geometry={nodes.Bush_leaf16_Leaf_0_4.geometry} material={materials.Leaf} rotation={[0.056, 1.042, -0.521]} scale={0.964} />
                  <mesh geometry={nodes.Bush_leaf17_Leaf_0_4.geometry} material={materials.Leaf} rotation={[-0.882, -1.098, -0.824]} />
                  <mesh geometry={nodes.Bush_leaf18_Leaf_0_4.geometry} material={materials.Leaf} rotation={[2.775, -0.722, -2.943]} scale={1.081} />
                  <mesh geometry={nodes.Bush_leaf19_Leaf_0_4.geometry} material={materials.Leaf} rotation={[-1.096, -0.353, 2.317]} />
                  <mesh geometry={nodes.Bush_leaf20_Leaf_0_4.geometry} material={materials.Leaf} position={[9.65, -0.937, -0.005]} rotation={[-2.932, 0.091, -2.794]} />
                </group>
                <group position={[9.175, -6.127, 14.116]} rotation={[0, -0.409, 0]}>
                  <mesh geometry={nodes.Bush_leaf13_Leaf_0_5.geometry} material={materials.Leaf} position={[-3.783, -4.046, 15.452]} rotation={[0, -1.257, 2.467]} />
                  <mesh geometry={nodes.Bush_leaf14_Leaf_0_5.geometry} material={materials.Leaf} position={[-2.838, -0.528, 0.816]} rotation={[2.791, -0.203, 2.88]} scale={0.914} />
                  <mesh geometry={nodes.Bush_leaf15_Leaf_0_5.geometry} material={materials.Leaf} position={[-1.452, -2.571, 12.134]} rotation={[-1.494, 1.509, 1.882]} scale={0.768} />
                  <mesh geometry={nodes.Bush_leaf16_Leaf_0_5.geometry} material={materials.Leaf} rotation={[0.056, 1.042, -0.521]} scale={0.964} />
                  <mesh geometry={nodes.Bush_leaf17_Leaf_0_5.geometry} material={materials.Leaf} rotation={[-0.882, -1.098, -0.824]} />
                  <mesh geometry={nodes.Bush_leaf18_Leaf_0_5.geometry} material={materials.Leaf} rotation={[2.775, -0.722, -2.943]} scale={1.081} />
                  <mesh geometry={nodes.Bush_leaf19_Leaf_0_5.geometry} material={materials.Leaf} rotation={[-1.096, -0.353, 2.317]} />
                  <mesh geometry={nodes.Bush_leaf20_Leaf_0_5.geometry} material={materials.Leaf} position={[9.65, -0.937, -0.005]} rotation={[-2.932, 0.091, -2.794]} />
                </group>
                <mesh geometry={nodes.Bush_leaf21_Leaf_0_1.geometry} material={materials.Leaf} position={[-1.452, -2.571, 12.134]} rotation={[-1.494, 1.509, 1.882]} scale={0.768} />
                <mesh geometry={nodes.Bush_leaf22_Leaf_0_1.geometry} material={materials.Leaf} position={[-3.783, -4.046, 15.452]} rotation={[0, -1.257, 2.467]} />
                <mesh geometry={nodes.Bush_leaf23_Leaf_0_1.geometry} material={materials.Leaf} position={[-2.838, -0.528, 0.816]} rotation={[2.791, -0.203, 2.88]} scale={0.914} />
                <mesh geometry={nodes.Bush_leaf24_Leaf_0_1.geometry} material={materials.Leaf} rotation={[2.775, -0.722, -2.943]} scale={1.081} />
                <mesh geometry={nodes.Bush_leaf25_Leaf_0_1.geometry} material={materials.Leaf} rotation={[-1.096, -0.353, 2.317]} />
                <mesh geometry={nodes.Bush_leaf26_Leaf_0_1.geometry} material={materials.Leaf} rotation={[-0.882, -1.098, -0.824]} />
                <mesh geometry={nodes.Bush_leaf27_Leaf_0_1.geometry} material={materials.Leaf} rotation={[0.056, 1.042, -0.521]} scale={0.964} />
                <mesh geometry={nodes.Bush_leaf28_Leaf_0_1.geometry} material={materials.Leaf} position={[9.65, -0.937, -0.005]} rotation={[-2.932, 0.091, -2.794]} />
              </group>
            </group>
            <group position={[12.44, 28.804, 9.471]} rotation={[0.718, 0.154, -0.123]}>
              <mesh geometry={nodes.Petal_shaped7_Petal1_0.geometry} material={materials.Petal1} rotation={[0, 1.309, -0.579]} />
              <mesh geometry={nodes.Petal_shaped9_Petal1_0.geometry} material={materials.Petal1} rotation={[-Math.PI, -0.348, -Math.PI]} />
              <mesh geometry={nodes.Petal_shaped8_Petal1_0.geometry} material={materials.Petal1} rotation={[2.706, -1.31, 3.012]} />
              <mesh geometry={nodes.Petal_shaped11_Petal1_0.geometry} material={materials.Petal1} rotation={[0, -0.856, -0.36]} />
              <mesh geometry={nodes.Petal_shaped13_Petal1_0.geometry} material={materials.Petal1} rotation={[-1.094, -1.359, -1.004]} />
              <mesh geometry={nodes.Petal_shaped5_Petal1_0.geometry} material={materials.Petal1} rotation={[0, -0.182, 0]} />
              <mesh geometry={nodes.Petal_shaped12_Petal1_0.geometry} material={materials.Petal1} rotation={[-0.122, 0.26, -0.342]} />
              <mesh geometry={nodes.Petal_shaped19_Petal1_0.geometry} material={materials.Petal1} rotation={[2.673, -0.864, -2.953]} />
              <mesh geometry={nodes.Petal_shaped10_Petal1_0.geometry} material={materials.Petal1} rotation={[-Math.PI, 0.702, -Math.PI]} />
              <mesh geometry={nodes.Petal_shaped6_Petal1_0.geometry} material={materials.Petal1} rotation={[0, 0.504, -0.714]} />
              <mesh geometry={nodes.Petal_shaped27_Petal1_0.geometry} material={materials.Petal1} rotation={[-2.956, 0.242, 1.904]} />
              <mesh geometry={nodes.Petal_shaped25_Petal1_0.geometry} material={materials.Petal1} rotation={[-0.147, -1.364, -0.938]} />
              <mesh geometry={nodes.Petal_shaped26_Petal1_0.geometry} material={materials.Petal1} rotation={[0.009, 0.221, -1.066]} />
              <mesh geometry={nodes.Petal_shaped20_Petal1_0.geometry} material={materials.Petal1} rotation={[-0.291, -0.532, 0.387]} />
              <mesh geometry={nodes.Petal_shaped23_Petal1_0.geometry} material={materials.Petal1} rotation={[-3.111, -0.528, 2.258]} />
              <mesh geometry={nodes.Petal_shaped21_Petal1_0.geometry} material={materials.Petal1} rotation={[-1.869, 1.301, 2.174]} />
              <mesh geometry={nodes.Petal_shaped22_Petal1_0.geometry} material={materials.Petal1} rotation={[-0.26, -0.396, -0.836]} />
              <mesh geometry={nodes.Petal_shaped24_Petal1_0.geometry} material={materials.Petal1} rotation={[-2.766, 1.252, 1.841]} />
              <mesh geometry={nodes.Petal_shaped17_Petal1_0.geometry} material={materials.Petal1} rotation={[3, -1.037, 2.717]} />
              <mesh geometry={nodes.Petal_shaped16_Petal1_0.geometry} material={materials.Petal1} rotation={[0.851, 1.071, -0.814]} />
              <mesh geometry={nodes.Petal_shaped14_Petal1_0.geometry} material={materials.Petal1} rotation={[3.074, 1.41, 2.907]} />
              <mesh geometry={nodes.Petal_shaped15_Petal1_0.geometry} material={materials.Petal1} rotation={[-Math.PI, 0.266, 2.602]} />
            </group>
            <group position={[-5.79, 32.512, -15.281]} rotation={[-0.984, 0.827, 0.419]}>
              <mesh geometry={nodes.Petal_shaped7_Petal1_0_1.geometry} material={materials.Petal1} rotation={[0, 1.309, -0.579]} />
              <mesh geometry={nodes.Petal_shaped9_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-Math.PI, -0.348, -Math.PI]} />
              <mesh geometry={nodes.Petal_shaped8_Petal1_0_1.geometry} material={materials.Petal1} rotation={[2.706, -1.31, 3.012]} />
              <mesh geometry={nodes.Petal_shaped11_Petal1_0_1.geometry} material={materials.Petal1} rotation={[0, -0.856, -0.36]} />
              <mesh geometry={nodes.Petal_shaped13_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-1.094, -1.359, -1.004]} />
              <mesh geometry={nodes.Petal_shaped5_Petal1_0_1.geometry} material={materials.Petal1} rotation={[0, -0.182, 0]} />
              <mesh geometry={nodes.Petal_shaped12_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-0.122, 0.26, -0.342]} />
              <mesh geometry={nodes.Petal_shaped19_Petal1_0_1.geometry} material={materials.Petal1} rotation={[2.673, -0.864, -2.953]} />
              <mesh geometry={nodes.Petal_shaped10_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-Math.PI, 0.702, -Math.PI]} />
              <mesh geometry={nodes.Petal_shaped6_Petal1_0_1.geometry} material={materials.Petal1} rotation={[0, 0.504, -0.714]} />
              <mesh geometry={nodes.Petal_shaped27_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-2.956, 0.242, 1.904]} />
              <mesh geometry={nodes.Petal_shaped25_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-0.147, -1.364, -0.938]} />
              <mesh geometry={nodes.Petal_shaped26_Petal1_0_1.geometry} material={materials.Petal1} rotation={[0.009, 0.221, -1.066]} />
              <mesh geometry={nodes.Petal_shaped20_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-0.291, -0.532, 0.387]} />
              <mesh geometry={nodes.Petal_shaped23_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-3.111, -0.528, 2.258]} />
              <mesh geometry={nodes.Petal_shaped21_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-1.869, 1.301, 2.174]} />
              <mesh geometry={nodes.Petal_shaped22_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-0.26, -0.396, -0.836]} />
              <mesh geometry={nodes.Petal_shaped24_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-2.766, 1.252, 1.841]} />
              <mesh geometry={nodes.Petal_shaped17_Petal1_0_1.geometry} material={materials.Petal1} rotation={[3, -1.037, 2.717]} />
              <mesh geometry={nodes.Petal_shaped16_Petal1_0_1.geometry} material={materials.Petal1} rotation={[0.851, 1.071, -0.814]} />
              <mesh geometry={nodes.Petal_shaped14_Petal1_0_1.geometry} material={materials.Petal1} rotation={[3.074, 1.41, 2.907]} />
              <mesh geometry={nodes.Petal_shaped15_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-Math.PI, 0.266, 2.602]} />
            </group>
            <group position={[-14.51, 26.053, 15.323]} rotation={[0.137, 0.43, 0.991]}>
              <mesh geometry={nodes.Petal_shaped7_Petal1_0_2.geometry} material={materials.Petal1} rotation={[0, 1.309, -0.579]} />
              <mesh geometry={nodes.Petal_shaped9_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-Math.PI, -0.348, Math.PI]} />
              <mesh geometry={nodes.Petal_shaped8_Petal1_0_2.geometry} material={materials.Petal1} rotation={[2.706, -1.31, 3.012]} />
              <mesh geometry={nodes.Petal_shaped11_Petal1_0_2.geometry} material={materials.Petal1} rotation={[0, -0.856, -0.36]} />
              <mesh geometry={nodes.Petal_shaped13_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-1.094, -1.359, -1.004]} />
              <mesh geometry={nodes.Petal_shaped5_Petal1_0_2.geometry} material={materials.Petal1} rotation={[0, -0.182, 0]} />
              <mesh geometry={nodes.Petal_shaped12_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-0.122, 0.26, -0.342]} />
              <mesh geometry={nodes.Petal_shaped19_Petal1_0_2.geometry} material={materials.Petal1} rotation={[2.673, -0.864, -2.953]} />
              <mesh geometry={nodes.Petal_shaped10_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-Math.PI, 0.702, -Math.PI]} />
              <mesh geometry={nodes.Petal_shaped6_Petal1_0_2.geometry} material={materials.Petal1} rotation={[0, 0.504, -0.714]} />
              <mesh geometry={nodes.Petal_shaped27_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-2.956, 0.242, 1.904]} />
              <mesh geometry={nodes.Petal_shaped25_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-0.147, -1.364, -0.938]} />
              <mesh geometry={nodes.Petal_shaped26_Petal1_0_2.geometry} material={materials.Petal1} rotation={[0.009, 0.221, -1.066]} />
              <mesh geometry={nodes.Petal_shaped20_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-0.291, -0.532, 0.387]} />
              <mesh geometry={nodes.Petal_shaped23_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-3.111, -0.528, 2.258]} />
              <mesh geometry={nodes.Petal_shaped21_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-1.869, 1.301, 2.174]} />
              <mesh geometry={nodes.Petal_shaped22_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-0.26, -0.396, -0.836]} />
              <mesh geometry={nodes.Petal_shaped24_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-2.766, 1.252, 1.841]} />
              <mesh geometry={nodes.Petal_shaped17_Petal1_0_2.geometry} material={materials.Petal1} rotation={[3, -1.037, 2.717]} />
              <mesh geometry={nodes.Petal_shaped16_Petal1_0_2.geometry} material={materials.Petal1} rotation={[0.851, 1.071, -0.814]} />
              <mesh geometry={nodes.Petal_shaped14_Petal1_0_2.geometry} material={materials.Petal1} rotation={[3.074, 1.41, 2.907]} />
              <mesh geometry={nodes.Petal_shaped15_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-Math.PI, 0.266, 2.602]} />
            </group>
          </group>
        </group>
      </group>

      <group ref={groupRef} {...props} dispose={null}>
        <group rotation={[-0.3, 0.2, 0]} scale={0.015} position={[-3, 3.5, -12]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[5.688, 0, -12]}>
              <group position={[-10.836, 15.481, 20.919]} rotation={[-2.937, -0.208, -3.099]}>
                <group position={[-20, 0, 0]} scale={1.111}>
                  <mesh geometry={nodes.Bush_leaf13_Leaf_0.geometry} material={materials.Leaf} position={[-3.783, -4.046, 15.452]} rotation={[0, -1.257, 2.467]} />
                  <mesh geometry={nodes.Bush_leaf14_Leaf_0.geometry} material={materials.Leaf} position={[-2.838, -0.528, 0.816]} rotation={[2.791, -0.203, 2.88]} scale={0.914} />
                  <mesh geometry={nodes.Bush_leaf15_Leaf_0.geometry} material={materials.Leaf} position={[-1.452, -2.571, 12.134]} rotation={[-1.494, 1.509, 1.882]} scale={0.768} />
                  <mesh geometry={nodes.Bush_leaf16_Leaf_0.geometry} material={materials.Leaf} rotation={[0.056, 1.042, -0.521]} scale={0.964} />
                  <mesh geometry={nodes.Bush_leaf17_Leaf_0.geometry} material={materials.Leaf} rotation={[-0.882, -1.098, -0.824]} />
                  <mesh geometry={nodes.Bush_leaf18_Leaf_0.geometry} material={materials.Leaf} rotation={[2.775, -0.722, -2.943]} scale={1.081} />
                  <mesh geometry={nodes.Bush_leaf19_Leaf_0.geometry} material={materials.Leaf} rotation={[-1.096, -0.353, 2.317]} />
                  <mesh geometry={nodes.Bush_leaf20_Leaf_0.geometry} material={materials.Leaf} position={[9.65, -0.937, -0.005]} rotation={[-2.932, 0.091, -2.794]} />
                </group>
                <group position={[-9.741, -2.987, 18.859]} rotation={[0, -0.686, 0]} scale={0.975}>
                  <mesh geometry={nodes.Bush_leaf13_Leaf_0_1.geometry} material={materials.Leaf} position={[-3.783, -4.046, 15.452]} rotation={[0, -1.257, 2.467]} />
                  <mesh geometry={nodes.Bush_leaf14_Leaf_0_1.geometry} material={materials.Leaf} position={[-2.838, -0.528, 0.816]} rotation={[2.791, -0.203, 2.88]} scale={0.914} />
                  <mesh geometry={nodes.Bush_leaf15_Leaf_0_1.geometry} material={materials.Leaf} position={[-1.452, -2.571, 12.134]} rotation={[-1.494, 1.509, 1.882]} scale={0.768} />
                  <mesh geometry={nodes.Bush_leaf16_Leaf_0_1.geometry} material={materials.Leaf} rotation={[0.056, 1.042, -0.521]} scale={0.964} />
                  <mesh geometry={nodes.Bush_leaf17_Leaf_0_1.geometry} material={materials.Leaf} rotation={[-0.882, -1.098, -0.824]} />
                  <mesh geometry={nodes.Bush_leaf18_Leaf_0_1.geometry} material={materials.Leaf} rotation={[2.775, -0.722, -2.943]} scale={1.081} />
                  <mesh geometry={nodes.Bush_leaf19_Leaf_0_1.geometry} material={materials.Leaf} rotation={[-1.096, -0.353, 2.317]} />
                  <mesh geometry={nodes.Bush_leaf20_Leaf_0_1.geometry} material={materials.Leaf} position={[9.65, -0.937, -0.005]} rotation={[-2.932, 0.091, -2.794]} />
                </group>
                <group position={[9.175, -6.127, 14.116]} rotation={[0, -0.409, 0]}>
                  <mesh geometry={nodes.Bush_leaf13_Leaf_0_2.geometry} material={materials.Leaf} position={[-3.783, -4.046, 15.452]} rotation={[0, -1.257, 2.467]} />
                  <mesh geometry={nodes.Bush_leaf14_Leaf_0_2.geometry} material={materials.Leaf} position={[-2.838, -0.528, 0.816]} rotation={[2.791, -0.203, 2.88]} scale={0.914} />
                  <mesh geometry={nodes.Bush_leaf15_Leaf_0_2.geometry} material={materials.Leaf} position={[-1.452, -2.571, 12.134]} rotation={[-1.494, 1.509, 1.882]} scale={0.768} />
                  <mesh geometry={nodes.Bush_leaf16_Leaf_0_2.geometry} material={materials.Leaf} rotation={[0.056, 1.042, -0.521]} scale={0.964} />
                  <mesh geometry={nodes.Bush_leaf17_Leaf_0_2.geometry} material={materials.Leaf} rotation={[-0.882, -1.098, -0.824]} />
                  <mesh geometry={nodes.Bush_leaf18_Leaf_0_2.geometry} material={materials.Leaf} rotation={[2.775, -0.722, -2.943]} scale={1.081} />
                  <mesh geometry={nodes.Bush_leaf19_Leaf_0_2.geometry} material={materials.Leaf} rotation={[-1.096, -0.353, 2.317]} />
                  <mesh geometry={nodes.Bush_leaf20_Leaf_0_2.geometry} material={materials.Leaf} position={[9.65, -0.937, -0.005]} rotation={[-2.932, 0.091, -2.794]} />
                </group>
                <mesh geometry={nodes.Bush_leaf21_Leaf_0.geometry} material={materials.Leaf} position={[-1.452, -2.571, 12.134]} rotation={[-1.494, 1.509, 1.882]} scale={0.768} />
                <mesh geometry={nodes.Bush_leaf22_Leaf_0.geometry} material={materials.Leaf} position={[-3.783, -4.046, 15.452]} rotation={[0, -1.257, 2.467]} />
                <mesh geometry={nodes.Bush_leaf23_Leaf_0.geometry} material={materials.Leaf} position={[-2.838, -0.528, 0.816]} rotation={[2.791, -0.203, 2.88]} scale={0.914} />
                <mesh geometry={nodes.Bush_leaf24_Leaf_0.geometry} material={materials.Leaf} rotation={[2.775, -0.722, -2.943]} scale={1.081} />
                <mesh geometry={nodes.Bush_leaf25_Leaf_0.geometry} material={materials.Leaf} rotation={[-1.096, -0.353, 2.317]} />
                <mesh geometry={nodes.Bush_leaf26_Leaf_0.geometry} material={materials.Leaf} rotation={[-0.882, -1.098, -0.824]} />
                <mesh geometry={nodes.Bush_leaf27_Leaf_0.geometry} material={materials.Leaf} rotation={[0.056, 1.042, -0.521]} scale={0.964} />
                <mesh geometry={nodes.Bush_leaf28_Leaf_0.geometry} material={materials.Leaf} position={[9.65, -0.937, -0.005]} rotation={[-2.932, 0.091, -2.794]} />
              </group>
              <group position={[0, 28, 0]}>
                <group position={[-20, 0, 0]} scale={1.111}>
                  <mesh geometry={nodes.Bush_leaf13_Leaf_0_3.geometry} material={materials.Leaf} position={[-3.783, -4.046, 15.452]} rotation={[0, -1.257, 2.467]} />
                  <mesh geometry={nodes.Bush_leaf14_Leaf_0_3.geometry} material={materials.Leaf} position={[-2.838, -0.528, 0.816]} rotation={[2.791, -0.203, 2.88]} scale={0.914} />
                  <mesh geometry={nodes.Bush_leaf15_Leaf_0_3.geometry} material={materials.Leaf} position={[-1.452, -2.571, 12.134]} rotation={[-1.494, 1.509, 1.882]} scale={0.768} />
                  <mesh geometry={nodes.Bush_leaf16_Leaf_0_3.geometry} material={materials.Leaf} rotation={[0.056, 1.042, -0.521]} scale={0.964} />
                  <mesh geometry={nodes.Bush_leaf17_Leaf_0_3.geometry} material={materials.Leaf} rotation={[-0.882, -1.098, -0.824]} />
                  <mesh geometry={nodes.Bush_leaf18_Leaf_0_3.geometry} material={materials.Leaf} rotation={[2.775, -0.722, -2.943]} scale={1.081} />
                  <mesh geometry={nodes.Bush_leaf19_Leaf_0_3.geometry} material={materials.Leaf} rotation={[-1.096, -0.353, 2.317]} />
                  <mesh geometry={nodes.Bush_leaf20_Leaf_0_3.geometry} material={materials.Leaf} position={[9.65, -0.937, -0.005]} rotation={[-2.932, 0.091, -2.794]} />
                </group>
                <group position={[-9.741, -2.987, 18.859]} rotation={[0, -0.686, 0]} scale={0.975}>
                  <mesh geometry={nodes.Bush_leaf13_Leaf_0_4.geometry} material={materials.Leaf} position={[-3.783, -4.046, 15.452]} rotation={[0, -1.257, 2.467]} />
                  <mesh geometry={nodes.Bush_leaf14_Leaf_0_4.geometry} material={materials.Leaf} position={[-2.838, -0.528, 0.816]} rotation={[2.791, -0.203, 2.88]} scale={0.914} />
                  <mesh geometry={nodes.Bush_leaf15_Leaf_0_4.geometry} material={materials.Leaf} position={[-1.452, -2.571, 12.134]} rotation={[-1.494, 1.509, 1.882]} scale={0.768} />
                  <mesh geometry={nodes.Bush_leaf16_Leaf_0_4.geometry} material={materials.Leaf} rotation={[0.056, 1.042, -0.521]} scale={0.964} />
                  <mesh geometry={nodes.Bush_leaf17_Leaf_0_4.geometry} material={materials.Leaf} rotation={[-0.882, -1.098, -0.824]} />
                  <mesh geometry={nodes.Bush_leaf18_Leaf_0_4.geometry} material={materials.Leaf} rotation={[2.775, -0.722, -2.943]} scale={1.081} />
                  <mesh geometry={nodes.Bush_leaf19_Leaf_0_4.geometry} material={materials.Leaf} rotation={[-1.096, -0.353, 2.317]} />
                  <mesh geometry={nodes.Bush_leaf20_Leaf_0_4.geometry} material={materials.Leaf} position={[9.65, -0.937, -0.005]} rotation={[-2.932, 0.091, -2.794]} />
                </group>
                <group position={[9.175, -6.127, 14.116]} rotation={[0, -0.409, 0]}>
                  <mesh geometry={nodes.Bush_leaf13_Leaf_0_5.geometry} material={materials.Leaf} position={[-3.783, -4.046, 15.452]} rotation={[0, -1.257, 2.467]} />
                  <mesh geometry={nodes.Bush_leaf14_Leaf_0_5.geometry} material={materials.Leaf} position={[-2.838, -0.528, 0.816]} rotation={[2.791, -0.203, 2.88]} scale={0.914} />
                  <mesh geometry={nodes.Bush_leaf15_Leaf_0_5.geometry} material={materials.Leaf} position={[-1.452, -2.571, 12.134]} rotation={[-1.494, 1.509, 1.882]} scale={0.768} />
                  <mesh geometry={nodes.Bush_leaf16_Leaf_0_5.geometry} material={materials.Leaf} rotation={[0.056, 1.042, -0.521]} scale={0.964} />
                  <mesh geometry={nodes.Bush_leaf17_Leaf_0_5.geometry} material={materials.Leaf} rotation={[-0.882, -1.098, -0.824]} />
                  <mesh geometry={nodes.Bush_leaf18_Leaf_0_5.geometry} material={materials.Leaf} rotation={[2.775, -0.722, -2.943]} scale={1.081} />
                  <mesh geometry={nodes.Bush_leaf19_Leaf_0_5.geometry} material={materials.Leaf} rotation={[-1.096, -0.353, 2.317]} />
                  <mesh geometry={nodes.Bush_leaf20_Leaf_0_5.geometry} material={materials.Leaf} position={[9.65, -0.937, -0.005]} rotation={[-2.932, 0.091, -2.794]} />
                </group>
                <mesh geometry={nodes.Bush_leaf21_Leaf_0_1.geometry} material={materials.Leaf} position={[-1.452, -2.571, 12.134]} rotation={[-1.494, 1.509, 1.882]} scale={0.768} />
                <mesh geometry={nodes.Bush_leaf22_Leaf_0_1.geometry} material={materials.Leaf} position={[-3.783, -4.046, 15.452]} rotation={[0, -1.257, 2.467]} />
                <mesh geometry={nodes.Bush_leaf23_Leaf_0_1.geometry} material={materials.Leaf} position={[-2.838, -0.528, 0.816]} rotation={[2.791, -0.203, 2.88]} scale={0.914} />
                <mesh geometry={nodes.Bush_leaf24_Leaf_0_1.geometry} material={materials.Leaf} rotation={[2.775, -0.722, -2.943]} scale={1.081} />
                <mesh geometry={nodes.Bush_leaf25_Leaf_0_1.geometry} material={materials.Leaf} rotation={[-1.096, -0.353, 2.317]} />
                <mesh geometry={nodes.Bush_leaf26_Leaf_0_1.geometry} material={materials.Leaf} rotation={[-0.882, -1.098, -0.824]} />
                <mesh geometry={nodes.Bush_leaf27_Leaf_0_1.geometry} material={materials.Leaf} rotation={[0.056, 1.042, -0.521]} scale={0.964} />
                <mesh geometry={nodes.Bush_leaf28_Leaf_0_1.geometry} material={materials.Leaf} position={[9.65, -0.937, -0.005]} rotation={[-2.932, 0.091, -2.794]} />
              </group>
            </group>
            <group position={[12.44, 28.804, 9.471]} rotation={[0.718, 0.154, -0.123]}>
              <mesh geometry={nodes.Petal_shaped7_Petal1_0.geometry} material={materials.Petal1} rotation={[0, 1.309, -0.579]} />
              <mesh geometry={nodes.Petal_shaped9_Petal1_0.geometry} material={materials.Petal1} rotation={[-Math.PI, -0.348, -Math.PI]} />
              <mesh geometry={nodes.Petal_shaped8_Petal1_0.geometry} material={materials.Petal1} rotation={[2.706, -1.31, 3.012]} />
              <mesh geometry={nodes.Petal_shaped11_Petal1_0.geometry} material={materials.Petal1} rotation={[0, -0.856, -0.36]} />
              <mesh geometry={nodes.Petal_shaped13_Petal1_0.geometry} material={materials.Petal1} rotation={[-1.094, -1.359, -1.004]} />
              <mesh geometry={nodes.Petal_shaped5_Petal1_0.geometry} material={materials.Petal1} rotation={[0, -0.182, 0]} />
              <mesh geometry={nodes.Petal_shaped12_Petal1_0.geometry} material={materials.Petal1} rotation={[-0.122, 0.26, -0.342]} />
              <mesh geometry={nodes.Petal_shaped19_Petal1_0.geometry} material={materials.Petal1} rotation={[2.673, -0.864, -2.953]} />
              <mesh geometry={nodes.Petal_shaped10_Petal1_0.geometry} material={materials.Petal1} rotation={[-Math.PI, 0.702, -Math.PI]} />
              <mesh geometry={nodes.Petal_shaped6_Petal1_0.geometry} material={materials.Petal1} rotation={[0, 0.504, -0.714]} />
              <mesh geometry={nodes.Petal_shaped27_Petal1_0.geometry} material={materials.Petal1} rotation={[-2.956, 0.242, 1.904]} />
              <mesh geometry={nodes.Petal_shaped25_Petal1_0.geometry} material={materials.Petal1} rotation={[-0.147, -1.364, -0.938]} />
              <mesh geometry={nodes.Petal_shaped26_Petal1_0.geometry} material={materials.Petal1} rotation={[0.009, 0.221, -1.066]} />
              <mesh geometry={nodes.Petal_shaped20_Petal1_0.geometry} material={materials.Petal1} rotation={[-0.291, -0.532, 0.387]} />
              <mesh geometry={nodes.Petal_shaped23_Petal1_0.geometry} material={materials.Petal1} rotation={[-3.111, -0.528, 2.258]} />
              <mesh geometry={nodes.Petal_shaped21_Petal1_0.geometry} material={materials.Petal1} rotation={[-1.869, 1.301, 2.174]} />
              <mesh geometry={nodes.Petal_shaped22_Petal1_0.geometry} material={materials.Petal1} rotation={[-0.26, -0.396, -0.836]} />
              <mesh geometry={nodes.Petal_shaped24_Petal1_0.geometry} material={materials.Petal1} rotation={[-2.766, 1.252, 1.841]} />
              <mesh geometry={nodes.Petal_shaped17_Petal1_0.geometry} material={materials.Petal1} rotation={[3, -1.037, 2.717]} />
              <mesh geometry={nodes.Petal_shaped16_Petal1_0.geometry} material={materials.Petal1} rotation={[0.851, 1.071, -0.814]} />
              <mesh geometry={nodes.Petal_shaped14_Petal1_0.geometry} material={materials.Petal1} rotation={[3.074, 1.41, 2.907]} />
              <mesh geometry={nodes.Petal_shaped15_Petal1_0.geometry} material={materials.Petal1} rotation={[-Math.PI, 0.266, 2.602]} />
            </group>
            <group position={[-5.79, 32.512, -15.281]} rotation={[-0.984, 0.827, 0.419]}>
              <mesh geometry={nodes.Petal_shaped7_Petal1_0_1.geometry} material={materials.Petal1} rotation={[0, 1.309, -0.579]} />
              <mesh geometry={nodes.Petal_shaped9_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-Math.PI, -0.348, -Math.PI]} />
              <mesh geometry={nodes.Petal_shaped8_Petal1_0_1.geometry} material={materials.Petal1} rotation={[2.706, -1.31, 3.012]} />
              <mesh geometry={nodes.Petal_shaped11_Petal1_0_1.geometry} material={materials.Petal1} rotation={[0, -0.856, -0.36]} />
              <mesh geometry={nodes.Petal_shaped13_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-1.094, -1.359, -1.004]} />
              <mesh geometry={nodes.Petal_shaped5_Petal1_0_1.geometry} material={materials.Petal1} rotation={[0, -0.182, 0]} />
              <mesh geometry={nodes.Petal_shaped12_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-0.122, 0.26, -0.342]} />
              <mesh geometry={nodes.Petal_shaped19_Petal1_0_1.geometry} material={materials.Petal1} rotation={[2.673, -0.864, -2.953]} />
              <mesh geometry={nodes.Petal_shaped10_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-Math.PI, 0.702, -Math.PI]} />
              <mesh geometry={nodes.Petal_shaped6_Petal1_0_1.geometry} material={materials.Petal1} rotation={[0, 0.504, -0.714]} />
              <mesh geometry={nodes.Petal_shaped27_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-2.956, 0.242, 1.904]} />
              <mesh geometry={nodes.Petal_shaped25_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-0.147, -1.364, -0.938]} />
              <mesh geometry={nodes.Petal_shaped26_Petal1_0_1.geometry} material={materials.Petal1} rotation={[0.009, 0.221, -1.066]} />
              <mesh geometry={nodes.Petal_shaped20_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-0.291, -0.532, 0.387]} />
              <mesh geometry={nodes.Petal_shaped23_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-3.111, -0.528, 2.258]} />
              <mesh geometry={nodes.Petal_shaped21_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-1.869, 1.301, 2.174]} />
              <mesh geometry={nodes.Petal_shaped22_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-0.26, -0.396, -0.836]} />
              <mesh geometry={nodes.Petal_shaped24_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-2.766, 1.252, 1.841]} />
              <mesh geometry={nodes.Petal_shaped17_Petal1_0_1.geometry} material={materials.Petal1} rotation={[3, -1.037, 2.717]} />
              <mesh geometry={nodes.Petal_shaped16_Petal1_0_1.geometry} material={materials.Petal1} rotation={[0.851, 1.071, -0.814]} />
              <mesh geometry={nodes.Petal_shaped14_Petal1_0_1.geometry} material={materials.Petal1} rotation={[3.074, 1.41, 2.907]} />
              <mesh geometry={nodes.Petal_shaped15_Petal1_0_1.geometry} material={materials.Petal1} rotation={[-Math.PI, 0.266, 2.602]} />
            </group>
            <group position={[-14.51, 26.053, 15.323]} rotation={[0.137, 0.43, 0.991]}>
              <mesh geometry={nodes.Petal_shaped7_Petal1_0_2.geometry} material={materials.Petal1} rotation={[0, 1.309, -0.579]} />
              <mesh geometry={nodes.Petal_shaped9_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-Math.PI, -0.348, Math.PI]} />
              <mesh geometry={nodes.Petal_shaped8_Petal1_0_2.geometry} material={materials.Petal1} rotation={[2.706, -1.31, 3.012]} />
              <mesh geometry={nodes.Petal_shaped11_Petal1_0_2.geometry} material={materials.Petal1} rotation={[0, -0.856, -0.36]} />
              <mesh geometry={nodes.Petal_shaped13_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-1.094, -1.359, -1.004]} />
              <mesh geometry={nodes.Petal_shaped5_Petal1_0_2.geometry} material={materials.Petal1} rotation={[0, -0.182, 0]} />
              <mesh geometry={nodes.Petal_shaped12_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-0.122, 0.26, -0.342]} />
              <mesh geometry={nodes.Petal_shaped19_Petal1_0_2.geometry} material={materials.Petal1} rotation={[2.673, -0.864, -2.953]} />
              <mesh geometry={nodes.Petal_shaped10_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-Math.PI, 0.702, -Math.PI]} />
              <mesh geometry={nodes.Petal_shaped6_Petal1_0_2.geometry} material={materials.Petal1} rotation={[0, 0.504, -0.714]} />
              <mesh geometry={nodes.Petal_shaped27_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-2.956, 0.242, 1.904]} />
              <mesh geometry={nodes.Petal_shaped25_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-0.147, -1.364, -0.938]} />
              <mesh geometry={nodes.Petal_shaped26_Petal1_0_2.geometry} material={materials.Petal1} rotation={[0.009, 0.221, -1.066]} />
              <mesh geometry={nodes.Petal_shaped20_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-0.291, -0.532, 0.387]} />
              <mesh geometry={nodes.Petal_shaped23_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-3.111, -0.528, 2.258]} />
              <mesh geometry={nodes.Petal_shaped21_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-1.869, 1.301, 2.174]} />
              <mesh geometry={nodes.Petal_shaped22_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-0.26, -0.396, -0.836]} />
              <mesh geometry={nodes.Petal_shaped24_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-2.766, 1.252, 1.841]} />
              <mesh geometry={nodes.Petal_shaped17_Petal1_0_2.geometry} material={materials.Petal1} rotation={[3, -1.037, 2.717]} />
              <mesh geometry={nodes.Petal_shaped16_Petal1_0_2.geometry} material={materials.Petal1} rotation={[0.851, 1.071, -0.814]} />
              <mesh geometry={nodes.Petal_shaped14_Petal1_0_2.geometry} material={materials.Petal1} rotation={[3.074, 1.41, 2.907]} />
              <mesh geometry={nodes.Petal_shaped15_Petal1_0_2.geometry} material={materials.Petal1} rotation={[-Math.PI, 0.266, 2.602]} />
            </group>
          </group>
        </group>
      </group>
    </>
  )
}

useGLTF.preload('/SunsetFlowerBush.gltf')
