/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 WoodFence.gltf 
Author: trentspi (https://sketchfab.com/trentspice)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fence-wood-e530c55db10348a3a547ef92149bdd10
Title: Fence (Wood)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function WoodFence(props) {
  const groupRef = useRef()
  const { nodes, materials } = useGLTF('/WoodFence.gltf')
  return (
    <>
      <group ref={groupRef} {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.WoodLog_Plank} position={[2.5, 12.4, 0]} rotation={[0, 0, 1.6]}/>
        </group>
      </group>

      <group ref={groupRef} {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.WoodLog_Plank} position={[4.6, 17, 0]} rotation={[0, 0, 2.5]}/>
        </group>
      </group>

      <group ref={groupRef} {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.WoodLog_Plank} position={[-4.1, 10.2, 0]} rotation={[0, 0, 1.2]}/>
        </group>
      </group>

      <group ref={groupRef} {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.WoodLog_Plank} position={[-8.1, 10.2, 0]} rotation={[0, 0, 1.2]}/>
        </group>
      </group>

      <group ref={groupRef} {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.WoodLog_Plank} position={[-12.9, 10.8, 0]} rotation={[0, 0, .5]}/>
        </group>
      </group>

      <group ref={groupRef} {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.WoodLog_Plank} position={[-16.1, 13.9, 0]} rotation={[0, 0, .1]}/>
        </group>
      </group>

      <group ref={groupRef} {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.WoodLog_Plank} position={[-17.9, 17.4, 0]} rotation={[0, 0, .1]}/>
        </group>
      </group>

      <group ref={groupRef} {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.WoodLog_Plank} position={[-19.7, 20.9, 0]} rotation={[0, 0, .1]}/>
        </group>
      </group>
    </>
  )
}

useGLTF.preload('/WoodFence.gltf')
