/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 WoodRaft.gltf 
Author: _SeF_ (https://sketchfab.com/_SeF_)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/raft-48fb810caf0941328a6619a9a948b565
Title: Raft
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function WoodRaft(props) {
  const groupRef = useRef()
  const { nodes, materials } = useGLTF('/WoodRaft.gltf')
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group position={[-1, 0, 24]} rotation={[-0.698, -Math.PI / 9, 0]} scale={0.0045}>
        <group position={[167.169, 46.363, -52.644]}>
          <mesh geometry={nodes.log_023_raft_0.geometry} material={materials.raft} />
          <mesh geometry={nodes.log_023_raft_0_1.geometry} material={materials.raft} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/WoodRaft.gltf')
