/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 WoodArch.gltf 
Author: darya-aet326 (https://sketchfab.com/darya-aet326)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/arch-047fb3ffe3a041878a659480aafff4af
Title: Arch
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function WoodArch(props) {
  const groupRef = useRef()
  const { nodes, materials } = useGLTF('/WoodArch.gltf')
  return (
    <group ref={groupRef} {...props} dispose={null} scale={.2}  position={[-2.5, 0, -12]} rotation={[0, 0.3, 0]}>
      <mesh geometry={nodes.pCylinder1_blinn2_0.geometry} material={materials.blinn2} />
    </group>
  )
}

useGLTF.preload('/WoodArch.gltf')
