# Generated by Django 4.2.4 on 2024-04-07 17:47

import dev_character_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_id', models.BigIntegerField(unique=True)),
                ('char_type', models.CharField(validators=[dev_character_app.validators.validate_char_type])),
                ('start_health', models.BigIntegerField()),
                ('start_stam', models.BigIntegerField()),
                ('start_armor', models.BigIntegerField()),
                ('start_dam', models.BigIntegerField()),
                ('start_att_sp', models.BigIntegerField()),
            ],
        ),
    ]
