# Generated by Django 4.2.4 on 2024-04-15 14:19

import dev_character_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_id', models.CharField(unique=True)),
                ('char_type', models.CharField(validators=[dev_character_app.validators.validate_char_type])),
                ('merchant', models.BooleanField(default=False)),
                ('quest_giver', models.BooleanField(default=False)),
                ('enemy', models.BooleanField(default=False)),
                ('boss', models.BooleanField(default=False)),
                ('start_health', models.BigIntegerField(default=100)),
                ('start_stam', models.BigIntegerField(default=100)),
                ('start_armor', models.BigIntegerField(default=50)),
                ('start_dam', models.BigIntegerField(default=10)),
                ('start_att_sp', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
            ],
        ),
    ]
