# Generated by Django 4.2.4 on 2024-04-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_character_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devcharacter',
            name='boss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devcharacter',
            name='enemy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devcharacter',
            name='merchant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devcharacter',
            name='quest_giver',
            field=models.BooleanField(default=False),
        ),
    ]
