# Generated by Django 4.2.4 on 2024-04-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_character_app', '0002_devcharacter_boss_devcharacter_enemy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devcharacter',
            name='start_armor',
            field=models.BigIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='devcharacter',
            name='start_att_sp',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='devcharacter',
            name='start_dam',
            field=models.BigIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='devcharacter',
            name='start_health',
            field=models.BigIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='devcharacter',
            name='start_stam',
            field=models.BigIntegerField(default=100),
        ),
    ]
