# Generated by Django 4.2.4 on 2024-04-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_character_app', '0003_alter_devcharacter_start_armor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devcharacter',
            name='char_id',
            field=models.CharField(unique=True),
        ),
    ]
