# Generated by Django 4.2.4 on 2024-04-07 17:47

import django.core.validators
from django.db import migrations, models
import saved_game_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff_level', models.CharField(validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(6), saved_game_app.validators.validate_diff_level])),
                ('save_date', models.TimeField()),
                ('scene_state', models.JSONField()),
            ],
        ),
    ]
