# Generated by Django 4.2.4 on 2024-04-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_game_app', '0003_alter_savedgame_save_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedgame',
            name='scene_state',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
