# Generated by Django 4.2.4 on 2024-04-14 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saved_game_app', '0004_alter_savedgame_scene_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedgame',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
