# Generated by Django 4.2.4 on 2024-04-14 23:46

import django.core.validators
from django.db import migrations, models
import saved_game_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('saved_game_app', '0005_alter_savedgame_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedgame',
            name='diff_level',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(7), saved_game_app.validators.validate_diff_level]),
        ),
    ]
