# Generated by Django 4.2.4 on 2024-04-15 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_game_app', '0007_alter_savedgame_save_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedgame',
            name='save_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
