# Generated by Django 4.2.4 on 2024-04-15 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saved_game_app', '0008_alter_savedgame_save_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedgame',
            name='save_date',
        ),
    ]
