# Generated by Django 4.2.4 on 2024-04-15 14:19

import dev_area_app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(25), dev_area_app.validators.validate_name])),
                ('order', models.BigIntegerField(unique=True)),
            ],
        ),
    ]
